twitter:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAMGsswEAAAAAuhEJSnr0eM2gORWL2jNWozzGUo8%3DutvmljQ6r5af5q2vXyfjuLGYSklzRMm6CMfc68vJ8AoZcD5Kc4
airtable:
  api_key: patASeCbFCje0QWQA.3778291b115ac191884d2f9c4c830e6dd69e1d0e4bd7220a9b2c04f5418d2ffe
  base_id: appYCZWcmNBXB2uUS
  table_name: tblJCXhcrCxDUJR3F