services:
  followfeed:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./output:/app/output
      - /var/log/followfeed.log:/var/log/followfeed.log
      - /var/log/followfeed_resources.log:/var/log/followfeed_resources.log
      - ./user_details.json:/app/user_details.json
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
      - PYTHONOPTIMIZE=2
    command: >
      sh -c "
        Xvfb :99 -screen 0 1280x720x24 -ac +extension GLX +render -noreset &
        (while true; do
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Memory Usage: $(free -m | awk 'NR==2{printf \"%.2f%%\", $3*100/$2}')\" >> /var/log/followfeed_resources.log;
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] CPU Usage: $(top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}')%\" >> /var/log/followfeed_resources.log;
          sleep 60;
        done) &
        python main.py
      "
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    stop_grace_period: 5m
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python main.py' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
