version: '3.8'

services:
  followfeed:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./output:/app/output
      - /var/log/followfeed.log:/var/log/followfeed.log
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    command: >
      sh -c "
        Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset &
        python main.py
      "
    deploy:
      resources:
        limits:
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    stop_grace_period: 5m
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python main.py' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
