name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}  # Add your droplet IP as a secret
        username: 'root'  # Default is root, change as necessary
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd /root/followfeed/  # Change to the directory of your project
          git pull origin master  # Ensure the branch name matches your workflow
